#ifndef MICROPY_HW_BOARD_NAME
#define MICROPY_HW_BOARD_NAME "ESP32-P4 Function EV Board"
#endif

#ifndef MICROPY_HW_MCU_NAME
#define MICROPY_HW_MCU_NAME "ESP32P4"
#endif

#define MICROPY_WRAP_TUD_CDC_RX_CB(name) __mp_##name
#define MICROPY_WRAP_TUD_EVENT_HOOK_CB(name) __mp_##name

#define MICROPY_HW_USB_VID 0x37C5
#define MICROPY_HW_USB_PID 0x1206
#define MICROPY_HW_USB_MANUFACTURER_STRING "OpenMV"
#define MICROPY_HW_USB_PRODUCT_FS_STRING "OpenMV Virtual Comm Port in HS Mode"
#define MICROPY_HW_USB_CDC_INTERFACE_STRING "OpenMV CDC"
#define MICROPY_HW_USB_MSC                 (1)
#define MICROPY_HW_USB_MSC_INTERFACE_STRING "OpenMV Flash"
#define MICROPY_HW_USB_MSC_INQUIRY_VENDOR_STRING "OpenMV  "
#define MICROPY_HW_USB_MSC_INQUIRY_PRODUCT_STRING "ESP32P4 Flash   "
#define MICROPY_HW_USB_MSC_INQUIRY_REVISION_STRING "1.00"

#define MICROPY_PY_ESPNOW                (0)

#define MICROPY_HW_ENABLE_SDCARD         (1)

#ifndef USB_SERIAL_JTAG_PACKET_SZ_BYTES
#define USB_SERIAL_JTAG_PACKET_SZ_BYTES (64)
#endif

#define MICROPY_HW_ENABLE_UART_REPL     (1)
#define MICROPY_PY_MACHINE_I2S          (1)

#ifndef MICROPY_PY_NETWORK_WLAN
#define MICROPY_PY_NETWORK_WLAN         (1)
#endif
#ifndef MICROPY_PY_BLUETOOTH
#define MICROPY_PY_BLUETOOTH            (0)
#endif
