#ifndef MICROPY_HW_BOARD_NAME
#define MICROPY_HW_BOARD_NAME "ESP32-P4X-EYE"
#endif

#ifndef MICROPY_HW_MCU_NAME
#define MICROPY_HW_MCU_NAME "ESP32P4"
#endif

#define MICROPY_HW_USB_MANUFACTURER_STRING "ESP-VISION"
#define MICROPY_HW_USB_PRODUCT_FS_STRING "ESP32-P4X-EYE MicroPython"

#define MICROPY_PY_ESPNOW                (0)

#define MICROPY_HW_ENABLE_SDCARD         (1)

#ifndef USB_SERIAL_JTAG_PACKET_SZ_BYTES
#define USB_SERIAL_JTAG_PACKET_SZ_BYTES  (64)
#endif

#define MICROPY_HW_ENABLE_UART_REPL      (1)

#define MICROPY_PY_MACHINE_I2S           (1)

#ifndef MICROPY_PY_NETWORK_WLAN
#define MICROPY_PY_NETWORK_WLAN          (0)
#endif

#ifndef MICROPY_PY_BLUETOOTH
#define MICROPY_PY_BLUETOOTH             (0)
#endif
